pipeline{
    agent any

    environment{
        REGION='us-east-1'
        S3_BUCKET='blog-app7'
        DISTRIBUTION_ID='E17PETT8G2VOVG'
        REACT_APP_API_URL='http://54.196.147.194:5000/api'
    }

    stages{
        stage('checkout'){
            steps{
                git credentialsId: 'github-cred', url: 'https://github.com/Ramezz07/blog-app.git'
            }
        }

        stage('install dependendies'){
            steps{
                dir('frontend'){
                sh "npm install"
                }
            }
        }

        stage('build static files'){
            steps{
                dir('frontend'){
                sh "REACT_APP_API_URL=${REACT_APP_API_URL} npm run build"
                }
            }
        }

        stage('move static file to s3 bucket'){
            steps{
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-cred']]){
                sh "/usr/local/bin/aws s3 sync frontend/build/ s3://${S3_BUCKET} --delete"
                }
            }
        }

        stage('invalidate cloudfront cache'){
            steps{
                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'aws-cred']]){
                sh "/usr/local/bin/aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths '/*'"
                }
            }
        }
    }
}
